### ISSUE TITLE
spawned messages are not shown in chat

### ISSUE THREAD

**Issue by Resoluciones** [Programie/TalkingMobs#1]
Hi!

Would it be possible you fix spawned messages not being showned in chat?

Thanks!

**Comment by Programie** [comment]
You mean mobs spawned with some spawn command like `/mob <mob>`? I also noticed that.

Spawning mobs with a monster egg actually triggers showing the messages. Maybe the spawn event is not fired if using a spawn command.

I will have a look into that issue.

**Comment by Resoluciones** [comment]
Hi!  Thanks for the reply!

Yes, I saw that when CreatureSpawnEvent.SpawnReason CUSTOM (When a creature is spawned by plugins).

Thanks!

**Comment by Programie** [comment]
I found the issue [right here](https://github.com/Programie/TalkingMobs/blob/master/src/main/java/com/selfcoders/talkingmobs/EventListener.java#L33). I had to add the `if` condition to prevent spam, but extending it for a check `spawnReason == CUSTOM` should fix it.
